package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"time"

	"github.com/joyvixtor/dock-scheduling-system/backend/crossdock/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/crossdock/internal/domain"
)

// ScanInboundPallet is the resolver for the scanInboundPallet field.
func (r *mutationResolver) ScanInboundPallet(ctx context.Context, sku string, quantity int, inboundDockID string) (*domain.TransferTask, error) {
	return r.MatchingEngine.ScanInboundPallet(ctx, sku, quantity, inboundDockID)
}

// AssignOperator is the resolver for the assignOperator field.
func (r *mutationResolver) AssignOperator(ctx context.Context, taskID string, operatorID string) (*domain.TransferTask, error) {
	return r.MatchingEngine.AssignOperator(ctx, taskID, operatorID)
}

// CompleteTransfer is the resolver for the completeTransfer field.
func (r *mutationResolver) CompleteTransfer(ctx context.Context, taskID string) (*domain.TransferTask, error) {
	return r.MatchingEngine.CompleteTransfer(ctx, taskID)
}

// ActiveTransferTasks is the resolver for the activeTransferTasks field.
func (r *queryResolver) ActiveTransferTasks(ctx context.Context) ([]*domain.TransferTask, error) {
	tasks, err := r.MatchingEngine.ActiveTransferTasks(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*domain.TransferTask, 0, len(tasks))
	for i := range tasks {
		task := tasks[i]
		result = append(result, &task)
	}

	return result, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *transferTaskResolver) CreatedAt(ctx context.Context, obj *domain.TransferTask) (string, error) {
	return obj.CreatedAt.UTC().Format(time.RFC3339), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// TransferTask returns generated.TransferTaskResolver implementation.
func (r *Resolver) TransferTask() generated.TransferTaskResolver { return &transferTaskResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	transferTaskResolver struct{ *Resolver }
)
