package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/joyvixtor/dock-scheduling-system/backend/crossdock/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/crossdock/internal/domain"
)

// FindProductBySku is the resolver for the findProductBySku field.
func (r *entityResolver) FindProductBySku(ctx context.Context, sku string) (*generated.Product, error) {
	tasks, err := r.MatchingEngine.ActiveTransferTasksBySKU(ctx, sku)
	if err != nil {
		return nil, err
	}

	filtered := make([]*domain.TransferTask, 0, len(tasks))
	for i := range tasks {
		task := tasks[i]
		filtered = append(filtered, &task)
	}

	return &generated.Product{
		Sku:                 sku,
		ActiveTransferTasks: filtered,
	}, nil
}

// FindTransferTaskByID is the resolver for the findTransferTaskByID field.
func (r *entityResolver) FindTransferTaskByID(ctx context.Context, id string) (*domain.TransferTask, error) {
	return r.MatchingEngine.FindTransferTaskByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
