package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/joyvixtor/dock-scheduling-system/backend/inbound/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/inbound/internal/domain"
)

// FindInboundDockByID is the resolver for the findInboundDockByID field.
func (r *entityResolver) FindInboundDockByID(ctx context.Context, id string) (*domain.InboundDock, error) {
	return r.Service.FindInboundDockByID(ctx, id)
}

// FindProductBySku is the resolver for the findProductBySku field.
func (r *entityResolver) FindProductBySku(ctx context.Context, sku string) (*domain.Product, error) {
	return r.Service.ProductBySKU(ctx, sku)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
