package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/joyvixtor/dock-scheduling-system/backend/inbound/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/inbound/internal/domain"
)

// UpdateInboundDockStatus is the resolver for the updateInboundDockStatus field.
func (r *mutationResolver) UpdateInboundDockStatus(ctx context.Context, id string, status domain.DockStatus) (*domain.InboundDock, error) {
	return r.Service.UpdateStatus(ctx, id, status)
}

// ActiveInboundDocks is the resolver for the activeInboundDocks field.
func (r *queryResolver) ActiveInboundDocks(ctx context.Context) ([]*domain.InboundDock, error) {
	docks, err := r.Service.ActiveInboundDocks(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*domain.InboundDock, 0, len(docks))
	for i := range docks {
		dock := docks[i]
		result = append(result, &dock)
	}

	return result, nil
}

// ProductBySku is the resolver for the productBySku field.
func (r *queryResolver) ProductBySku(ctx context.Context, sku string) (*domain.Product, error) {
	return r.Service.ProductBySKU(ctx, sku)
}

// InboundDockByID is the resolver for the inboundDockById field.
func (r *queryResolver) InboundDockByID(ctx context.Context, id string) (*domain.InboundDock, error) {
	return r.Service.FindInboundDockByID(ctx, id)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
