package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/joyvixtor/dock-scheduling-system/backend/inbound/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/inbound/internal/domain"
)

// ActiveInboundDocks is the resolver for the activeInboundDocks field.
func (r *queryResolver) ActiveInboundDocks(ctx context.Context) ([]*domain.InboundDock, error) {
	docks, err := r.Service.ActiveInboundDocks(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*domain.InboundDock, 0, len(docks))
	for i := range docks {
		dock := docks[i]
		result = append(result, &dock)
	}

	return result, nil
}

// ProductBySku is the resolver for the productBySku field.
func (r *queryResolver) ProductBySku(ctx context.Context, sku string) (*domain.Product, error) {
	return r.Service.ProductBySKU(ctx, sku)
}

// InboundDockByID is the resolver for the inboundDockById field.
func (r *queryResolver) InboundDockByID(ctx context.Context, id string) (*domain.InboundDock, error) {
	panic(fmt.Errorf("not implemented: InboundDockByID - inboundDockById"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) InboundDockById(ctx context.Context, id string) (*domain.InboundDock, error) {
	return r.Service.FindInboundDockByID(ctx, id)
}
*/
