package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/joyvixtor/dock-scheduling-system/backend/inbound/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/inbound/internal/domain"
)

// ActiveInboundDocks is the resolver for the activeInboundDocks field.
func (r *queryResolver) ActiveInboundDocks(ctx context.Context) ([]*domain.InboundDock, error) {
	docks, err := r.Service.ActiveInboundDocks(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*domain.InboundDock, 0, len(docks))
	for i := range docks {
		dock := docks[i]
		result = append(result, &dock)
	}

	return result, nil
}

// ProductBySku is the resolver for the productBySku field.
func (r *queryResolver) ProductBySku(ctx context.Context, sku string) (*domain.Product, error) {
	return r.Service.ProductBySKU(ctx, sku)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
