supergraph:
  listen: 0.0.0.0:8000
  path: /graphql
  introspection: true

cors:
  origins:
    - http://localhost:5173
  allow_credentials: true
  allow_headers:
    - content-type
    - authorization
    - apollo-require-preflight
    - x-apollo-operation-name
  expose_headers:
    - content-length
    - content-type
  methods:
    - GET
    - POST
    - OPTIONS

homepage:
  enabled: true

include_subgraph_errors:
  all: true
