package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/joyvixtor/dock-scheduling-system/backend/outbound/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/outbound/internal/domain"
)

// FindOutboundDockByID is the resolver for the findOutboundDockByID field.
func (r *entityResolver) FindOutboundDockByID(ctx context.Context, id string) (*domain.OutboundDock, error) {
	return r.Service.FindOutboundDockByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
