package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/joyvixtor/dock-scheduling-system/backend/outbound/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/outbound/internal/domain"
)

// UpdateOutboundDockStatus is the resolver for the updateOutboundDockStatus field.
func (r *mutationResolver) UpdateOutboundDockStatus(ctx context.Context, id string, status domain.DockStatus) (*domain.OutboundDock, error) {
	return r.Service.UpdateStatus(ctx, id, status)
}

// ActiveOutboundDocks is the resolver for the activeOutboundDocks field.
func (r *queryResolver) ActiveOutboundDocks(ctx context.Context) ([]*domain.OutboundDock, error) {
	docks, err := r.Service.ActiveOutboundDocks(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*domain.OutboundDock, 0, len(docks))
	for i := range docks {
		dock := docks[i]
		result = append(result, &dock)
	}

	return result, nil
}

// ClosestEmptyOutboundDock is the resolver for the closestEmptyOutboundDock field.
func (r *queryResolver) ClosestEmptyOutboundDock(ctx context.Context, locationX int, locationY int) (*domain.OutboundDock, error) {
	return r.Service.ClosestEmptyOutboundDock(ctx, locationX, locationY)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
