package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"os"

	"github.com/joyvixtor/dock-scheduling-system/backend/appointments/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/appointments/internal/domain"
)

// StartTime is the resolver for the startTime field.
func (r *appointmentResolver) StartTime(ctx context.Context, obj *domain.Appointment) (string, error) {
	return obj.StartTime.UTC().Format("2006-01-02T15:04:05Z"), nil
}

// EndTime is the resolver for the endTime field.
func (r *appointmentResolver) EndTime(ctx context.Context, obj *domain.Appointment) (string, error) {
	return obj.EndTime.UTC().Format("2006-01-02T15:04:05Z"), nil
}

// OrderID is the resolver for the orderId field.
func (r *appointmentResolver) OrderID(ctx context.Context, obj *domain.Appointment) (*string, error) {
	return obj.OrderID, nil
}

// CreateAppointment is the resolver for the createAppointment field.
func (r *mutationResolver) CreateAppointment(ctx context.Context, input domain.CreateAppointmentInput) (*domain.Appointment, error) {
	appt, err := r.Service.CreateAppointment(ctx, input)
	if err != nil {
		fmt.Printf("ERROR in CreateAppointment: %v\n", err)
		import_os_err := err.Error()
		_ = ctx // avoid unused ctx
		// Write to a local file in the workspace
		_ = os.WriteFile("appt_err.txt", []byte(import_os_err), 0644)
	}
	return appt, err
}

// UpdateAppointmentStatus is the resolver for the updateAppointmentStatus field.
func (r *mutationResolver) UpdateAppointmentStatus(ctx context.Context, id string, status domain.AppointmentStatus) (*domain.Appointment, error) {
	return r.Service.UpdateAppointmentStatus(ctx, id, status)
}

// AppointmentsByDate is the resolver for the appointmentsByDate field.
func (r *queryResolver) AppointmentsByDate(ctx context.Context, date string) ([]*domain.Appointment, error) {
	return r.Service.GetAppointmentsByDate(ctx, date)
}

// OrderID is the resolver for the orderId field.
func (r *createAppointmentInputResolver) OrderID(ctx context.Context, obj *domain.CreateAppointmentInput, data *string) error {
	obj.OrderID = data
	return nil
}

// Appointment returns generated.AppointmentResolver implementation.
func (r *Resolver) Appointment() generated.AppointmentResolver { return &appointmentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// CreateAppointmentInput returns generated.CreateAppointmentInputResolver implementation.
func (r *Resolver) CreateAppointmentInput() generated.CreateAppointmentInputResolver {
	return &createAppointmentInputResolver{r}
}

type (
	appointmentResolver            struct{ *Resolver }
	mutationResolver               struct{ *Resolver }
	queryResolver                  struct{ *Resolver }
	createAppointmentInputResolver struct{ *Resolver }
)
