package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"

	"github.com/joyvixtor/dock-scheduling-system/backend/appointments/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/appointments/internal/domain"
)

// FindAppointmentByID is the resolver for the findAppointmentByID field.
func (r *entityResolver) FindAppointmentByID(ctx context.Context, id string) (*domain.Appointment, error) {
	panic(fmt.Errorf("not implemented: FindAppointmentByID - findAppointmentByID"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
