package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/joyvixtor/dock-scheduling-system/backend/orders/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/orders/internal/domain"
)

// FindOrderByID is the resolver for the findOrderByID field.
func (r *entityResolver) FindOrderByID(ctx context.Context, id string) (*domain.Order, error) {
	return r.OrderService.FindByID(ctx, id)
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
