package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/joyvixtor/dock-scheduling-system/backend/orders/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/orders/internal/domain"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, sku string, quantity int) (*domain.Order, error) {
	return r.OrderService.CreateOrder(ctx, sku, quantity)
}

// CompleteOrder is the resolver for the completeOrder field.
func (r *mutationResolver) CompleteOrder(ctx context.Context, id string) (*domain.Order, error) {
	return r.OrderService.CompleteOrder(ctx, id)
}

// PendingDemandBySku is the resolver for the pendingDemandBySku field.
func (r *queryResolver) PendingDemandBySku(ctx context.Context, sku string) (int, error) {
	return r.OrderService.PendingDemandBySKU(ctx, sku)
}

// PendingOrders is the resolver for the pendingOrders field.
func (r *queryResolver) PendingOrders(ctx context.Context, sku string) ([]*domain.Order, error) {
	orders, err := r.OrderService.PendingOrdersBySKU(ctx, sku)
	if err != nil {
		return nil, err
	}

	result := make([]*domain.Order, 0, len(orders))
	for i := range orders {
		order := orders[i]
		result = append(result, &order)
	}

	return result, nil
}

// AllPendingOrders is the resolver for the allPendingOrders field.
func (r *queryResolver) AllPendingOrders(ctx context.Context) ([]*domain.Order, error) {
	orders, err := r.OrderService.AllPendingOrders(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*domain.Order, 0, len(orders))
	for i := range orders {
		order := orders[i]
		result = append(result, &order)
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
