package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/joyvixtor/dock-scheduling-system/backend/orders/internal/delivery/graphql/generated"
	"github.com/joyvixtor/dock-scheduling-system/backend/orders/internal/domain"
)

// PendingDemandBySku is the resolver for the pendingDemandBySku field.
func (r *queryResolver) PendingDemandBySku(ctx context.Context, sku string) (int, error) {
	return r.OrderService.PendingDemandBySKU(ctx, sku)
}

// PendingOrders is the resolver for the pendingOrders field.
func (r *queryResolver) PendingOrders(ctx context.Context, sku string) ([]*domain.Order, error) {
	orders, err := r.OrderService.PendingOrdersBySKU(ctx, sku)
	if err != nil {
		return nil, err
	}

	result := make([]*domain.Order, 0, len(orders))
	for i := range orders {
		order := orders[i]
		result = append(result, &order)
	}

	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
